// <auto-generated />
using System;
using Cu_ServicePattern_Movies.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cu_ServicePattern_Movies.Core.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20251105140502_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 5
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 6
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 5
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 6
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 7
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 8
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 7
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 8
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 9
                        },
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 10
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 9
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 10
                        });
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Brad",
                            Lastname = "Pitt"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Julia",
                            Lastname = "Roberts"
                        });
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Universal Pictures"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sony Pictures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warner Bros."
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marvel Studios"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Amblin Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Village Roadshow Pictures"
                        },
                        new
                        {
                            Id = 7,
                            Name = "20th Century Fox"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Paramount Pictures"
                        });
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Martin",
                            Lastname = "Scorsese"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Ron",
                            Lastname = "Wood"
                        });
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Price = 50.00m,
                            ReleaseDate = new DateTime(2007, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Transformers"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Price = 55.00m,
                            ReleaseDate = new DateTime(2009, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Transformers: Revenge of the Fallen"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 3,
                            Price = 60.00m,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            Price = 65.00m,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 4,
                            Price = 70.00m,
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 3,
                            Price = 58.00m,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 5,
                            Price = 52.00m,
                            ReleaseDate = new DateTime(2015, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic World"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 6,
                            Price = 48.00m,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 7,
                            Price = 68.00m,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 8,
                            Price = 72.00m,
                            ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun: Maverick"
                        });
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Review = "Very good!!",
                            Score = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            Review = "good!!",
                            Score = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            Review = "Ok",
                            Score = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 2,
                            Review = "Average..",
                            Score = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Bart",
                            Lastname = "Soete",
                            Username = "bart.soete@movierating.com"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Karel",
                            Lastname = "Soete",
                            Username = "karel.soete@movierating.com"
                        });
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.Property<int>("DirectorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("DirectorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("DirectorMovie");

                    b.HasData(
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            DirectorsId = 1,
                            MoviesId = 2
                        },
                        new
                        {
                            DirectorsId = 2,
                            MoviesId = 2
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Movie", b =>
                {
                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.Company", "Company")
                        .WithMany("Movies")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Rating", b =>
                {
                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DirectorMovie", b =>
                {
                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.Director", null)
                        .WithMany()
                        .HasForeignKey("DirectorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cu_ServicePattern_Movies.Core.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Company", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.Movie", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Cu_ServicePattern_Movies.Core.Entities.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
